<%
   require 'bcdatabase'
    bcdb = Bcdatabase.load RAILS_ROOT+'/config/bcdatabase/'
%>

<%= bcdb.development :bcdatabase, :inav_development %>
<%= bcdb.staging :bcstage, :inav_staging %>
<%= bcdb.production :bcprod, :inav %>

test:
  adapter: postgresql
  database: inav_test
  username: inav_test
  password: password
  host: localhost