<%
   require 'bcdatabase'
    bcdb = Bcdatabase.load INAV_CONFIG[:bcdatabase][:path]
%>

<%= bcdb.development :bcdevelopment, :inav_development %>
<%= bcdb.test :bcdevelopment, :inav_test %>
<%= bcdb.staging :bcstaging, :inav_staging %>
<%= bcdb.production :bcproduction, :inav %>
