<%
   require 'bcdatabase'
    bcdb = Bcdatabase::DatabaseConfigurations.new(INAV_CONFIG_FILE)
%>

<%= bcdb.development :inav, :inav_development %>
<%= bcdb.test :inav, :inav_test %>
<%= bcdb.staging :inav, :inav_staging %>
<%= bcdb.production :inav, :inav %>
