# config/psc.yml
development:
  psc_canonical_uri: http://127.0.0.1:8080/psc/
  psc_service_uri: http://127.0.0.1:8080/psc/auth/cas_security_check
  psc_site: testsite
  psc_rest_url: http://127.0.0.1:8080/psc/api/v1/

test:
  psc_canonical_uri: http://127.0.0.1:8080/psc/
  psc_service_uri: http://127.0.0.1:8080/psc/auth/cas_security_check
  psc_site: testsite
  psc_rest_url: http://127.0.0.1:8080/psc/api/v1/

hudson:
  psc_canonical_uri: http://127.0.0.1:8080/psc/
  psc_service_uri: http://127.0.0.1:8080/psc/auth/cas_security_check
  psc_site: testsite
  psc_rest_url: http://127.0.0.1:8080/psc/api/v1/

staging:
  psc_canonical_uri: https://inav-staging.nubic.northwestern.edu/psc/
  psc_service_uri: https://inav-staging.nubic.northwestern.edu/psc/auth/cas_security_check
  psc_site: ship
  psc_rest_url: https://inav-staging.nubic.northwestern.edu/psc/api/v1/

production:
  psc_canonical_uri: https://inav.nubic.northwestern.edu/psc/
  psc_service_uri: https://inav.nubic.northwestern.edu/psc/auth/cas_security_check
  psc_site: ship
  psc_rest_url: https://inav.nubic.northwestern.edu/psc/api/v1/